FROM alpine:3.12

ARG VERSION=3.00-r0

RUN apk add --no-cache "transmission-daemon=${VERSION}"

VOLUME /config
VOLUME /downloads

EXPOSE 9091
EXPOSE 51413

ENTRYPOINT ["transmission-daemon", "-f", "-g", "/config"]
