apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: ingress
  annotations:
    metallb.universe.tf/allow-shared-ip: ap4y.home
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
    name: https
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.1.50
