apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: chat-certificate
spec:
  secretName: chat-certificate
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - chat.ap4y.me
