apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dovecot
        image: ap4y/dovecot
        ports:
        - containerPort: 993
        - containerPort: 2525
        volumeMounts:
        - name: config
          mountPath: /etc/dovecot
          readOnly: true
        - name: certs
          mountPath: /etc/ssl/dovecot
          readOnly: true
        - name: maildir
          mountPath: /mail
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 2525
        readinessProbe:
          tcpSocket:
            port: 2525
      volumes:
      - name: config
        configMap:
          name: dovecot-config
      - name: certs
        secret:
          secretName: cloud-certificate
      - name: maildir
        hostPath:
          path: /storage/kubernetes/vmail
