apiVersion: v1
kind: Service
metadata:
  name: dovecot
  annotations:
    metallb.universe.tf/allow-shared-ip: ap4y.home
spec:
  ports:
  - port: 993
    targetPort: 993
    nodePort: 30993
    protocol: TCP
    name: imaps
  selector:
    app: dovecot
  type: LoadBalancer
  loadBalancerIP: 192.168.1.50
