apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cloud-certificate
spec:
  secretName: cloud-certificate
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - cloud.ap4y.me
