FROM alpine:3.11

ARG OPENSMTPD_VER=6.6.4p1-r0

RUN apk add --no-cache "opensmtpd=${OPENSMTPD_VER}"; \
  adduser -D ap4y

VOLUME /var/spool/smtpd

EXPOSE 25
EXPOSE 587

ENTRYPOINT ["smtpd", "-d", "-f", "/etc/smtpd/smtpd.conf"]
