FROM docker.io/alpine:3.22

ARG OPENSMTPD_VER=7.7.0_p0-r0

RUN apk add --no-cache "opensmtpd=${OPENSMTPD_VER}"; \
  adduser -D ap4y; \
  adduser -D j0li

VOLUME /var/spool/smtpd

EXPOSE 25
EXPOSE 587

ENTRYPOINT ["smtpd", "-d", "-f", "/etc/smtpd/smtpd.conf"]
