apiVersion: v1
kind: Service
metadata:
  name: smtpd
  annotations:
    metallb.universe.tf/allow-shared-ip: ap4y.home
spec:
  ports:
  - port: 25
    targetPort: 25
    protocol: TCP
    nodePort: 30025
    name: smtp
  - port: 587
    targetPort: 587
    nodePort: 30587
    protocol: TCP
    name: submission
  selector:
    app: smtpd
  type: LoadBalancer
  loadBalancerIP: 192.168.1.50
