FROM docker.io/alpine:3.22

ARG PROSODY_VER=0.12.5-r1

RUN apk add --no-cache "prosody=${PROSODY_VER}";

EXPOSE 5222
EXPOSE 5000
EXPOSE 5280
EXPOSE 5281

VOLUME /var/lib/prosody

ENTRYPOINT ["prosody", "-F", "--config", "/prosody/prosody.cfg.lua"]
