apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ap4y-me-certificate
spec:
  secretName: ap4y-me-certificate
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - ap4y.me
