on:
  push:
    branches: [ master ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: transmission
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ap4y/transmission
        tag_with_sha: true
        dockerfile: Dockerfile.transmission
