on:
  push:
    branches: [ master ]

docker_settings: &docker_settings
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}
  tag_with_sha: true

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: transmission
      uses: docker/build-push-action@v1.1.0
      with:
        <<: *docker_settings
        repository: ap4y/transmission
        dockerfile: Dockerfile.transmission
