on:
  push:
    branches: [ master ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: transmission
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ap4y/transmission
        tags: 3.00-r0
        dockerfile: transmission/Dockerfile.transmission
    - name: dovecot
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ap4y/dovecot
        tags: 2.3.10.1-r0
        dockerfile: dovecot/Dockerfile.dovecot
